import type { ThemeVars } from './types';

export function toThemeVars(vars: ThemeVars) {
  return {
    colors: {
      bgPrimary: vars['--blink-bg-primary'],
      button: vars['--blink-button'],
      buttonDisabled: vars['--blink-button-disabled'],
      buttonSuccess: vars['--blink-button-success'],
      iconError: vars['--blink-icon-error'],
      iconPrimary: vars['--blink-icon-primary'],
      iconWarning: vars['--blink-icon-warning'],
      inputBg: vars['--blink-input-bg'],
      inputStroke: vars['--blink-input-stroke'],
      inputStrokeDisabled: vars['--blink-input-stroke-disabled'],
      inputStrokeError: vars['--blink-input-stroke-error'],
      inputStrokeSelected: vars['--blink-input-stroke-selected'],
      strokeError: vars['--blink-stroke-error'],
      strokePrimary: vars['--blink-stroke-primary'],
      strokeSecondary: vars['--blink-stroke-secondary'],
      strokeWarning: vars['--blink-stroke-warning'],
      textBrand: vars['--blink-text-brand'],
      textButton: vars['--blink-text-button'],
      textButtonDisabled: vars['--blink-text-button-disabled'],
      textButtonSuccess: vars['--blink-text-button-success'],
      textError: vars['--blink-text-error'],
      textInput: vars['--blink-text-input'],
      textInputDisabled: vars['--blink-text-input-disabled'],
      textInputPlaceholder: vars['--blink-text-input-placeholder'],
      textLink: vars['--blink-text-link'],
      textPrimary: vars['--blink-text-primary'],
      textSecondary: vars['--blink-text-secondary'],
      textSuccess: vars['--blink-text-success'],
      textWarning: vars['--blink-text-warning'],
      transparentError: vars['--blink-transparent-error'],
      transparentGrey: vars['--blink-transparent-grey'],
      transparentWarning: vars['--blink-transparent-warning'],
    },
    borderRadii: {
      lg: vars['--blink-border-radius-rounded-lg'],
      xl: vars['--blink-border-radius-rounded-xl'],
      '2xl': vars['--blink-border-radius-rounded-2xl'],
      button: vars['--blink-border-radius-rounded-button'],
      input: vars['--blink-border-radius-rounded-input'],
    },
  };
}
